services:
  backend:
    build: .
    environment:
      - GIN_MODE=debug
    container_name: trip-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml # Mount config file
    depends_on:
      - mysql
      - redis
    dns: 
      - 114.114.114.114 # 国内通用DNS
      - 8.8.8.8 # 备用（Google DNS）

  redis:
    image: m.daocloud.io/docker.io/library/redis:7
    container_name: trip-redis
    ports:
      - "6378:6379"
  
  mysql:
    image: m.daocloud.io/docker.io/library/mysql:8.0
    container_name: trip-mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    env_file:
      - .env
    volumes:
      - ../database:/docker-entrypoint-initdb.d/ # 初始化脚本
      - mysql_data:/var/lib/mysql  # 数据持久化

volumes:
  mysql_data: