CREATE TABLE `trip_routes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '路线ID',
  `trip_id` bigint(20) unsigned NOT NULL COMMENT '关联行程ID',
  `origin_place_id` bigint(20) unsigned DEFAULT NULL COMMENT '起点地点ID',
  `origin_lng` decimal(10,6) NOT NULL COMMENT '起点经度',
  `origin_lat` decimal(10,6) NOT NULL COMMENT '起点纬度',
  `destination_place_id` bigint(20) unsigned DEFAULT NULL COMMENT '终点地点ID',
  `destination_lng` decimal(10,6) NOT NULL COMMENT '终点经度',
  `destination_lat` decimal(10,6) NOT NULL COMMENT '终点纬度',
  `waypoints` json DEFAULT NULL COMMENT '途经点信息',
  `optimized_order` json DEFAULT NULL COMMENT '优化后的顺序',
  `travel_mode` enum('driving','walking','bicycling','transit') NOT NULL COMMENT '出行方式',
  `strategy` varchar(10) DEFAULT NULL COMMENT '路线策略',
  `total_distance` decimal(10,2) DEFAULT NULL COMMENT '总距离(公里)',
  `total_duration` int(11) DEFAULT NULL COMMENT '总时长(分钟)',
  `path_data` json DEFAULT NULL COMMENT '路径详细数据',
  `polyline` text COMMENT '路线坐标串',
  `amap_route_id` varchar(100) DEFAULT NULL COMMENT '高德路线ID',
  `api_response_cache` json DEFAULT NULL COMMENT 'API完整响应缓存',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '是否当前激活路线',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_trip_id` (`trip_id`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='行程路线表';